unnamed:
  yamlSettings:
    SOCIALACCOUNT_PROVIDERS:
      github:
        APP:
          secret: ENC[AES256_GCM,data:Oz29LedE1FFZkaw21xoW/ctJkwzYT68hoHypCqdodBflumRJaJPZkkHnhGNRMwEh3gY7F7dVrt0JrhsjzF/pg6E5eI+UcfFslRxXRNerWy4=,iv:qTLugN/c6w+k8FmkuHxyEXoR46Ng8Ak000E4sE6zLXA=,tag:onRmqq2hU6pZI6UB61zyJA==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2024-09-06T18:27:04Z"
      enc: CiUA4OM7eBSb0cMpAVjRGF14pktFOfj8YpSMuZDYd1lBigSunRUIEkkA5dG1Q8/wvlZKzQhlH2qbiv+639ckJlt4ilpDUTL73pjdGsnlwj+TwNN1b8bk9QyROgq28QE5IL+fak8mKUasyNxC2+5VKiJU
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-09-06T18:27:55Z"
  mac: ENC[AES256_GCM,data:f6b6fbkoapfHwTRqgXAS8ju7ZtxfIlaNNZwF0fdoHONyVdDF/ues/dekUnV1gpW5FX/4/7qscfmI2bGSLJhk2Uir8rewUeGm0Em/OWS+ki8iLdNqpLsR5+xbFnytJokg8yHRuYGjp3pNG2JtdcZT2QxQxiGSQl9zQhrs3c1rxKo=,iv:i005rXWbvJ64cfNMPRxRu0PP8oB4PrlujY0NZhQyu6Q=,tag:9wC1HYcDQIkQLb2di4fYgw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
