frx-challenges:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      cert-manager.io/cluster-issuer: letsencrypt-prod
  pvc:
    storageClassName: premium-rwo
    storage: 10Gi

  adminUsers:
    - GeorgianaElena
    - yuvipanda
    - rhoadesScholar

  extraInitContainers:
    gcs-pull:
      name: gcs-pull
      image: google/cloud-sdk:497.0.0-stable
      command:
        - /bin/sh
        - -c
        # use printf so we don't interpret the \n in service account keys's private key
        # Delete empty directories, since `gcloud storage rsync` with `--delete-unmatched-destination-objects`
        # does not seem to actually delete directories created, only the leaf objects (sometimes).
        - |
          export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/tmp/gcloud-auth && \
          printf '%s' "$SERVICE_ACCOUNT_JSON_KEY" > $CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE && \
          mkdir -p /opt/state/truth/ && \
          gcloud storage rsync --recursive --delete-unmatched-destination-objects \
            gs://cellmap-challenge-ground-truth-fake/gt.zarr /opt/state/truth/gt.zarr && \
          find /opt/state/truth/ -type d -empty -delete
      volumeMounts:
        - name: storage
          mountPath: /opt/state

  yamlSettings:
    overrides:
      # Make sure OAuth2 redirect URI is https, not http
      ACCOUNT_DEFAULT_HTTP_PROTOCOL: https
      # Image is built from https://github.com/janelia-cellmap/cellmap-segmentation-challenge
      EVALUATOR_DOCKER_IMAGE: quay.io/2i2c/cellmap-segmentation-challenge-evaluator:797a892d742d
      EVALUATOR_DOCKER_CMD:
        - 'csc'
        - 'evaluate'
        - '--truth_path'
        - '/opt/gt.zarr'
        - '--submission_path'
        - '{submission_path}'
        - '--result_file'
        - '{result_path}'
      EVALUATOR_DOCKER_EXTRA_BINDS:
        - /opt/state/truth/gt.zarr:/opt/gt.zarr:ro
      EVALUATOR_DOCKER_CONTAINER_CPU_LIMIT: 1.5
      EVALUATION_DISPLAY_CONFIG:
        - result_key: overall_semantic_score
          display_name: Semantic Score
          ordering: descending
          ordering_priority: 3
        - result_key: overall_instance_score
          display_name: Instance Score
          ordering: descending
          ordering_priority: 2
        - result_key: overall_score
          display_name: Score
          ordering: descending
          ordering_priority: 1
      SITE_SUBMISSION_FORM_SCHEMA:
          type: object
          properties:
              repo:
                  type: "string"
                  title: "Repository"
                  helpText: "Link to repository containing source of this model (if public)"
                  format: "uri"
              institution:
                type: "string"
                title: "Institution"
              team:
                type: "string"
                title: "Team Name"
      SITE_NAME: CellMap Challenge
      SITE_LOGO_URL: header-logo
      SITE_PAGE_HEADER_IMAGE_URL: home-hero-image
      SITE_FOOTER_HTML: |-
        <style>
          footer, footer a {
            color: #838286;
            text-decoration: none
          }
        </style>
        <footer class="text-center break-bootstrap-container py-4 text-uppercase">
          <div class="container">
            <div class="d-flex flex-column gap-3">
              <div>
                <a href="https://www.janelia.org/project-team/cellmap">
                  <img src="/file/footer-logo-cellmap" height="48px" width="auto" />
                </a>
                <a href="https://www.janelia.org/">
                  <img
                    class="ms-2"
                    src="/file/footer-logo-hhmi"
                    height="48px"
                    width="auto"
                  />
                </a>
                <a href="https://2i2c.org/">
                  <img
                    class="ms-2"
                    src="/file/2i2c-blue-logo"
                    height="48px"
                    width="auto"
                  />
                </a>
              </div>
              <div>
                <small>
                  <p>
                    © 2024 CellMap Segmentation Challenge. <br />
                    This challenge is brought to you by the CellMap Project Team at
                    HHMI's Janelia Research Campus
                  </p>
                </small>
              </div>
              <div>
                <small>
                  <p>
                    <a href="mailto:cellmapchallenge@janelia.hhmi.org">Contact Us</a> |
                    <a href="https://openorganelle.janelia.org/">OpenOrganelle</a>
                  </p>
                </small>
              </div>
            </div>
          </div>
        </footer>
        <script defer data-domain="cellmapchallenge.janelia.org" src="https://plausible.io/js/script.js"></script>
