unnamed:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      cert-manager.io/cluster-issuer: letsencrypt-prod
  pvc:
    storageClassName: premium-rwo
    storage: 10Gi

  adminUsers:
    - GeorgianaElena
    - yuvipanda

  extraInitContainers:
    gcs-pull:
      name: gcs-pull
      image: google/cloud-sdk:497.0.0-stable
      command:
        - /bin/sh
        - -c
        # use printf so we don't interpret the \n in service account keys's private key
        - |
          export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/tmp/gcloud-auth && \
          printf '%s' "$SERVICE_ACCOUNT_JSON_KEY" > $CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE && \
          cat $CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE && \
          mkdir -p /opt/state/truth/ && \
          gcloud storage rsync --recursive --delete-unmatched-destination-objects \
            gs://cellmap-challenge-ground-truth-fake/gt.zarr /opt/state/truth/gt.zarr
      volumeMounts:
        - name: storage
          mountPath: /opt/state

  yamlSettings:
    overrides:
      EVALUATOR_DOCKER_IMAGE: us-west2-docker.pkg.dev/segmentation-challenge/cellmap-challenge/evaluator:latest
      EVALUATOR_DOCKER_CMD:
        - python
        - -m
        - cellmap_segmentation_challenge.evaluate
        - --truth-path
        - /opt/gt.zarr
      EVALUATOR_DOCKER_EXTRA_BINDS:
        - /opt/state/truth/gt.zarr:/opt/gt.zarr:ro
      EVALUATOR_DOCKER_CONTAINER_CPU_LIMIT: 1.5
      EVALUATOR_DOCKER_AUTH:
        username: "_json_key"
        serveraddress: "us-west2-docker.pkg.dev"
      SITE_NAME: CellMap Challenge
      SITE_LOGO_URL: header-logo
      SITE_PAGE_HEADER_IMAGE_URL: home-hero-image
      SITE_FOOTER_HTML: |-
        <style>
          footer, footer a {
            color: #838286;
            text-decoration: none
          }
        </style>
        <footer class="text-center break-bootstrap-container py-4 text-uppercase">
          <div class="container">
            <div class="d-flex flex-column gap-3">
              <div>
                <a href="https://www.janelia.org/project-team/cellmap">
                  <img src="/file/footer-logo-cellmap" height="48px" width="auto" />
                </a>
                <a href="https://www.janelia.org/">
                  <img
                    class="ms-2"
                    src="/file/footer-logo-hhmi"
                    height="48px"
                    width="auto"
                  />
                </a>
                <a href="https://2i2c.org/">
                  <img
                    class="ms-2"
                    src="/file/2i2c-blue-logo"
                    height="48px"
                    width="auto"
                  />
                </a>
              </div>
              <div>
                <small>
                  <p>
                    © 2024 CellMap Segmentation Challenge. <br />
                    This challenge is brought to you by the CellMap Project Team at
                    HHMI's Janelia Research Campus
                  </p>
                </small>
              </div>
              <div>
                <small>
                  <p>
                    <a href="mailto:cellmapchallenge@janelia.hhmi.org">Contact Us</a> |
                    <a href="https://openorganelle.janelia.org/">OpenOrganelle</a>
                  </p>
                </small>
              </div>
            </div>
          </div>
        </footer>
        <script defer data-domain="cellmapchallenge.janelia.org" src="https://plausible.io/js/script.js"></script>
