unnamed:
  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    hosts:
      - cellmapchallenge.2i2c.cloud

  yamlSettings:
    enabled: true
    overrides:
      ALLOWED_HOSTS:
        - cellmapchallenge.2i2c.cloud

  # The nfs share /db/prod was created manually
  nfs:
    pv:
      serverIP: 10.12.39.58
