unnamed:
  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    hosts:
      - staging.cellmapchallenge.2i2c.cloud

  yamlSettings:
    enabled: true
    overrides:
      ALLOWED_HOSTS:
        - staging.cellmapchallenge.2i2c.cloud
      DEBUG: True
