cert-manager:
  namespace: support
  crds:
    # This option decides if the CRDs should be installed
    # as part of the Helm installation.
    enabled: true
    # This option makes it so that the "helm.sh/resource-policy": keep
    # annotation is added to the CRD.
    keep: true

ingress-nginx:
  controller:
    resources:
      requests:
        # Overprovision requests, just in case
        cpu: 200m
        memory: 512Mi
