frx-challenges:
  resources:
    # Very generous memory requests and limits
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 8Gi
      cpu: 2
  nginx:
    resources:
      requests:
        memory: 512Mi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 2
  pvc:
    storage: 50Gi
  ingress:
    hosts:
      - cellmapchallenge.2i2c.cloud
      - cellmapchallenge.janelia.org
    tls:
      - secretName: https-auto-tls
        hosts:
          - cellmapchallenge.2i2c.cloud
          - cellmapchallenge.janelia.org

  yamlSettings:
    overrides:
      ALLOWED_HOSTS:
        - cellmapchallenge.2i2c.cloud
        - cellmapchallenge.janelia.org
      CSRF_TRUSTED_ORIGINS:
        - https://cellmapchallenge.2i2c.cloud
        - https://cellmapchallenge.janelia.org
      # Disable debug mode for prod instance
      DEBUG: False
      SOCIALACCOUNT_PROVIDERS:
        github:
          APP:
            client_id: Ov23liSODletCDyM8sa8
            redirect_uri: https://cellmapchallenge.janelia.org/accounts/github/login/callback/
          VERIFIED_EMAIL: True
      CHALLENGE_STATE: "RUNNING"
