unnamed:
  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    hosts:
      - cellmapchallenge.2i2c.cloud

  # The nfs share /db/prod was created manually
  nfs:
    pv:
      serverIP: 10.12.39.58

  adminUsers:
    - GeorgianaElena
    - yuvipanda

  yamlSettings:
    enabled: true
    overrides:
      ALLOWED_HOSTS:
        - cellmapchallenge.2i2c.cloud
      DEBUG: True
      SOCIALACCOUNT_PROVIDERS:
        github:
          APP:
            client_id: Ov23liSODletCDyM8sa8
            redirect_uri: http://cellmapchallenge.2i2c.cloud/accounts/github/login/callback/
          VERIFIED_EMAIL: True
      CHALLENGE_STATE: "NOT_STARTED"
      FOOTER: |
        <script defer data-domain="cellmapchallenge.2i2c.cloud" src="https://plausible.io/js/script.js"></script>
