unnamed:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - cellmapchallenge.2i2c.cloud
    tls:
      - secretName: https-auto-tls
        hosts:
          - cellmapchallenge.2i2c.cloud

  pvc:
    storageClassName: premium-rwo

  adminUsers:
    - GeorgianaElena
    - yuvipanda

  yamlSettings:
    enabled: true
    overrides:
      ALLOWED_HOSTS:
        - cellmapchallenge.2i2c.cloud
      CSRF_TRUSTED_ORIGINS:
        - https://cellmapchallenge.2i2c.cloud
      DEBUG: True
      SOCIALACCOUNT_PROVIDERS:
        github:
          APP:
            client_id: Ov23liSODletCDyM8sa8
            redirect_uri: http://cellmapchallenge.2i2c.cloud/accounts/github/login/callback/
          VERIFIED_EMAIL: True
      CHALLENGE_STATE: "NOT_STARTED"
      FOOTER: |
        <script defer data-domain="cellmapchallenge.2i2c.cloud" src="https://plausible.io/js/script.js"></script>
