# This is a _local composite GitHub action_ that helps us reuse CI logic across
# different workflows and jobs by referencing this action in a job's step.
#
# > A composite action allows you to combine multiple workflow steps within one
# > action.
#
# This local action can be referenced like this from a job:
#
#   steps:
#     - uses: ./.github/actions/setup-deploy
#       with:
#         GCP_KMS_DECRYPTOR_KEY: ${{ secrets.GCP_KMS_DECRYPTOR_KEY }}
#
# General action configuration reference:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#about-yaml-syntax-for-github-actions
#
name: "Setup the deployer script for use to deploy"
description: >-
  Setups the deployer script by loading credentials and installing library
  dependencies and relevant tools needed to interact with encrypted files,
  kubernetes clusters, and container registries. `gcloud` already available in
  the github virtual environment is not re-installed but `helm` is pinned to
  avoid issues of a changing version.

inputs:
  GCP_KMS_DECRYPTOR_KEY:
    description: >-
      A Google Cloud Service Account Key with KMS Decryption privileges. This allows
      us to unlock our sops-encrypted secrets required for a deploy.
    required: true

# runs (for composite actions) configuration reference:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
#
# Note that while this section looks almost like the steps of a job in a
# workflow, it is different!
#
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - uses: azure/setup-helm@v4
      with:
        version: v3.14.4

    - uses: azure/setup-kubectl@v4
      with:
        version: "v1.28.8"

    - name: Install sops
      uses: mdgreenwald/mozilla-sops-action@v1.6.0

    # Install pre-requisite for "gcloud container clusters get-credentials"
    # command with a modern k8s client.
    #
    # A manual install step has been needed as they opted to not provide it in
    # the github-runner image. See
    # https://github.com/actions/runner-images/issues/5925#issuecomment-1216417721.
    #
    - name: Install gke-gcloud-auth-plugin
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

        sudo apt-get update -y
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
      shell: bash

    - name: Setup sops credentials to decrypt repo secrets
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ inputs.GCP_KMS_DECRYPTOR_KEY }}"
