name: Deploy the staging app

on:
  push:
    branches:
      - main
    paths:
      - helm-charts/app/Chart.yaml
      - helm-charts/apps/staging.values.yaml
  workflow_dispatch:

jobs:
  upgrade-support-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup deploy
        uses: ./.github/actions/setup-deploy
        with:
          GCP_KMS_DECRYPTOR_KEY: ${{ secrets.GCP_KMS_DECRYPTOR_KEY }}

      - name: Update helm dependencies
        run: |
          helm dependency update helm-charts/app

      - name: Deploy staging app
        run: |
          python3 deployer.py app --namespace=staging --values_file staging.values.yaml
