name: Deploy the support chart

on:
  push:
    branches:
      - main
    paths:
      - helm-charts/support/**
  workflow_dispatch:

env:
  TERM: xterm
  # This may not be required any more, and it may depend on the kubectl version
  # we use etc as well. For now, we have it added to avoid issues.
  USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

jobs:
  upgrade-support-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup deploy
        uses: ./.github/actions/setup-deploy
        with:
          GCP_KMS_DECRYPTOR_KEY: ${{ secrets.GCP_KMS_DECRYPTOR_KEY }}

      - name: Update helm dependencies
        run: |
          helm dependency update helm-charts/support

      - name: Upgrade support chart
        run: |
          python3 deployer.py support --namespace=support
